version: '2'

services:
  nginx:
    build: './docks/nginx/.'
    ports:
      - '8080:80'
    volumes_from:
      - web:ro
    depends_on:
      - web

  web:
    build: './sources/.'
    image: 'websource'
    ports:
      - '127.0.0.1:8000:8000'
    env_file: '.env'
    command: 'gunicorn _project_.wsgi:application -w 2 -b :8000 --capture-output --enable-stdio-inheritance --log-level=debug --access-logfile=- --log-file=-'
    volumes:
      - 'cachedata:/cache'
      - 'mediadata:/media'
    depends_on:
      - postgres
      - redis

  postgres:
    container_name: 'postgres'
    image: 'mdillon/postgis:9.6'
    ports:
      - '127.0.0.1:5432:5432'
    volumes:
      - 'pgdata:/var/lib/postgresql/data/'

  redis:
    container_name: 'redis'
    image: 'redis:3.2.0'
    ports:
      - '127.0.0.1:6379:6379'
    volumes:
      - 'redisdata:/data'

volumes:
  pgdata:
  redisdata:
  cachedata:
  mediadata:
